<a href="https://colab.research.google.com/github/ZiYu-Huang/Practices-for-Beginners/blob/main/Day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#向量化
'''
相同大小的陣列之間進行運算，稱作為 向量化，
即同時對整批的資料一起做運算、
對相同位置的數值之間做運算
'''

In [3]:
test_1 = np.array([[1,2,3],
          [2,3,4]])
test_2 = np.array([[-1,-2,-3],
          [-2,-3,-4]])

In [4]:
test_1 + test_2  ##輸出結果為[[1+(-1),2+(-2),3+(-3)],
           #     [2+(-2),3+(-3),4+(-4)]]] 

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
test_1 - test_2  ##輸出結果為[[1-(-1),2-(-2),3-(-3)],
           #     [2-(-2),3-(-3),4-(-4)]]] 

array([[2, 4, 6],
       [4, 6, 8]])

###廣播
######不同大小的陣列之間進行運算，稱作為 廣播

In [7]:
test_1 = np.array([[1,2,3],[2,3,4]]) #shape(3,3)的陣列
test_2 = np.array([-1,-2,-3])    #shape為(3)的陣列

In [9]:
test_1 + test_2        #當此兩者不同大小陣列間做運算時，test_3會每一個raw(列)分別對test_4做運算

array([[0, 0, 0],
       [1, 1, 1]])

In [ ]:
test_1 - test_2

array([[2, 4, 6],
       [3, 5, 7]])

In [ ]:
test_0 = np.array([1,2,3,4,5,6])
test_0 + 1            #也可以同時對一個數值做運算

array([2, 3, 4, 5, 6, 7])

In [ ]:
test_3 = np.array([[1,2,3],[2,3,4],[4,5,6]])
test_4 = np.array([-1,-2,-3])

In [ ]:
test_3 + test_4  ##輸出結果為[[1+(-1),2+(-2),3+(-3)], test_3第一個raw對test_4做運算
           #     [2+(-1),3+(-2),4+(-3)],  test_3第二個raw對test_4做運算
           #     [3+(-1),4+(-2),5+(-3)],  test_3第三個raw對test_4做運算          

array([[0, 0, 0],
       [1, 1, 1],
       [3, 3, 3]])

#全域函式
#####對於一般常見的運算函式(如:abs取絕對值、log、square平方)做向量化的動作

In [ ]:
test_5 = np.array([-1,2,-3,4,-5,6,-7,8])

In [ ]:
np.square(test_5) #平方

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [ ]:
np.abs(test_5) #絕對值

array([1, 2, 3, 4, 5, 6, 7, 8])